// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package service

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AuthorizeProcessRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsAuthorizeProcessRequest(buf []byte, offset flatbuffers.UOffsetT) *AuthorizeProcessRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AuthorizeProcessRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *AuthorizeProcessRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AuthorizeProcessRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AuthorizeProcessRequest) OldPid() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AuthorizeProcessRequest) MutateOldPid(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *AuthorizeProcessRequest) NewPid() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AuthorizeProcessRequest) MutateNewPid(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func AuthorizeProcessRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func AuthorizeProcessRequestAddOldPid(builder *flatbuffers.Builder, oldPid uint32) {
	builder.PrependUint32Slot(0, oldPid, 0)
}
func AuthorizeProcessRequestAddNewPid(builder *flatbuffers.Builder, newPid uint32) {
	builder.PrependUint32Slot(1, newPid, 0)
}
func AuthorizeProcessRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
