// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package service

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AuthorizeProcessResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsAuthorizeProcessResponse(buf []byte, offset flatbuffers.UOffsetT) *AuthorizeProcessResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AuthorizeProcessResponse{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *AuthorizeProcessResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AuthorizeProcessResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func AuthorizeProcessResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func AuthorizeProcessResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
